sudo: true

dist: trusty

language: c

before_install:
  - .travis/install-dependencies.sh 

script:
  - ./functional_tests/code-review-c-test.sh -p code-review-c-c -d functional_tests/test_data
  - .travis/unit-test.sh
